### PR TITLE
App 36 create review page UI

### PR DESCRIPTION
**Pull request by Kyle-Mie**
Adds UI for Review Page. No ties to backend. Added some comment's with my thoughts for how the linking could be done. I'm thinking we should add an array of 'SolutionIds' to the petition table so we can easily generate the suggestion cards.

### CODE REVIEW

**Comment by Colby-M** [comment]
pull in the main branch to get the actual data from the petitions. You will probably need to change a few things but nothing to dramatic

**Review by Colby-M — CHANGES_REQUESTED** [review]
pull in main

**Comment by Kyle-Mie** [comment]
Linked to data when clicking review button on discovery page. There are errors when directly clicking on review. Will fix them tomorrow

**Comment by Kyle-Mie** [comment]
Review page is finally linked up. I will fix some styling and clean up code in a later pull request.

**Comment by Kyle-Mie** [comment]
Seems like the redirect pull request may have broken the discover page when clicking on the review buttons.

**Review by Colby-M — APPROVED** [review]
Only issue was the wizard store breaking the router. I fixed it in this PR to work, but I am going to look into the actual solution with the routing.

**Pull request merged**
